### ISSUE TITLE
Can't open file

### ISSUE THREAD

**Issue by Spleens1** [Otakubuns/Sims4-DRP#4]
Hello.
I've read through your code because I've got exceptions when using your mod.
1. I don't see a check which either creates the log file or opens it accordingly
2. even when creating the log file by hand in the ts4 documents folder, it still can't find the file
The error: `Failure: 'main' (main) [Errno 2] No such file or directory: 'C:\\Users\\Username\\Documents\\Electronic Arts\\The Sims 4\\DiscordRPCLog.txt' (FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Username\\Documents\\Electronic Arts\\The Sims 4\\DiscordRPCLog.txt')`

**Comment by Spleens1** [comment]
I think I might've found your issue. My sims folder is in german (because the game installed in my native language) so the path isn't `...\The Sims 4\DiscordRPCLog.txt`, rather than `...\Die Sims 4\DiscordRPCLog.txt`

**Comment by Otakubuns** [comment]
I didn't even realize that would be a problem. The reason that the file is even there is because the presence is updating too quickly and the presence update is being discarded so I will have to look for a way to remove that file and get the presence to update still. 
Thank you so much for your input and apologies it's not working I'll get working on a fix for that.

**Comment by Spleens1** [comment]
> I didn't even realize that would be a problem. The reason that the file is even there is because the presence is updating too quickly and the presence update is being discarded so I will have to look for a way to remove that file and get the presence to update still. Thank you so much for your input and apologies it's not working I'll get working on a fix for that.

that seems like a easy to fix issue which doesn't even need a file.
you could create a dict and update that dict every time (I don't remember what was in that file but a dict should be a good solution) and use the `asyncio.sleep` function on a set amount of seconds to run the function again.

``
`update_dict = True`
``
`async def update_dict (self): `
`    while update_dict: `
`        await asyncio.sleep(10) `
`        # do the dict stuff `
``

A simple while loop which runs indefinite times because update_dict is set to true

**Comment by Otakubuns** [comment]
The file itself honestly doesn't help for issue tracking but was in place of a delay as asyncio isn't in Sims 4 limited python library(I would have used pypresence but since it uses a lot of libraries that Sims doesn't have it was just a hassle) and in debugging, I was writing to a file to see the output but once it wasn't writing there wasn't a delay and would kill the presence.

I'm not very proficient at Python but have seemed to find a fix so I don't have to have a file being made that isn't needed.

Thanks for all your help and input on this! I appreciate it a lot.

**Comment by Spleens1** [comment]
No worries man. Just devs helping each other out.

Ah damn okay I didn't know sims doesn't have async support ... Jesus which libary doesn't support async anymore these days 🙄 
U need a Tester for your mod?

**Comment by Otakubuns** [comment]
It may use other means for asynchronous tasks but from decompiling the Python folders the game uses its a very small amount of libraries so it's why I'm using such a bare-bones discord wrapper. (This game is very annoying to mod coding wise so I just make do with what i can lol) 

I am using a function that emulates that delay sort of and 0.5 seconds seems to be enough time but ya you can test it out:

I only tested it a few times but it seems to work, was also tested on bare bones game without mods

**Comment by Spleens1** [comment]
yeah I know. Sims is a dogshit game to mod. I've been there and thankfully never returned.
Jup can confirm, the mod works perfectly fine.
![image](https://github.com/Otakubuns/Sims4-DRP/assets/61100599/40beb766-f639-4c20-8fdb-0d40a4303b70)

**Comment by Otakubuns** [comment]
I've spent 30+ hours just looking into the games code and debugging this so good idea not to make a mod for it lmao

Thanks for testing it, gonna push it and release the new update.

**Comment by Otakubuns** [comment]
I left out a try/catch so do make sure to download the new version cause that one has it in there(for if u don't have Discord open when ur playing it'll cause an exception)
https://github.com/Otakubuns/Sims4-DRP/releases/tag/1.0.5

**Comment by Spleens1** [comment]
thanks mate!
