### ISSUE TITLE
Rich presence breaking after ~3 hours

### ISSUE THREAD

**Issue by Spleens1** [Otakubuns/Sims4-DRP#5]
Heya!

Sorry to bother you once more but I found out after I played for ~3 hours straight, the presence broke and the default Sims 4 presence gets shown again.
I know, this isn't really that big of an issue but I thought I'd let you know!

Keep up the great work! :)

**Comment by eltorrento** [comment]
It looks like it happens randomly - sometimes it keeps for 20 hours without issues but sometimes it breaks after 1 hour. I thought it could be caused by network issues but I unplugged/plugged network cable and rich presence still works so I can't reproduce this issue right now.

**Comment by Otakubuns** [comment]
Apologies for such a late response(was finishing up college classes). I've pinpointed it on my game specifically as any error happening in the game kills the rich presence along with it. I've now added a reconnection when the presence gets updated so that may fix the problem. Haven't played a ton with the implemented fixes besides restarting my Discord client a million times so that fix should at least help reestablish the connection and redo the presence if it somehow breaks. If you still have that issue after this update please let me know!

**Comment by Spleens1** [comment]
I've been avoiding Sims 4 for the past couple of months but I'll give it a shot today and see if it works!

**Comment by eltorrento** [comment]
> I've been avoiding Sims 4 for the past couple of months but I'll give it a shot today and see if it works!

I'm still sitting on 1.107.151.1020 and works fine. I haven't updated the game to Lovestruck patch yet because most of major mods are still broken so I will update the game later and will give more info about this mod (it usually takes 1-2 weeks for mod fixes).

**Comment by Spleens1** [comment]
yeah I didn't pay attention to when the update was released and updated my game. Now I have to suffer with these broken mods xD

**Comment by Otakubuns** [comment]
was hoping this update my mod would be spared, should be expected not lol. I will work on it today since I updated my game already and see how long it'll take to fix. Thanks for the heads up on it.

**Comment by Otakubuns** [comment]
Actually, its fine, thank God. Seems this update didn't change any of the functions my mod hooks into. Looking like no update needed for this mod. No guarantee that it'll work with all the broken mods since it may hook into the same ones and destroy the presence along with it. Time to wait for all the other mods to update now.

**Comment by Spleens1** [comment]
> Actually, its fine, thank God. Seems this update didn't change any of the functions my mod hooks into. Looking like no update needed for this mod. No guarantee that it'll work with all the broken mods since it may hook into the same ones and destroy the presence along with it. Time to wait for all the other mods to update now.

yeah I figured your mod shouldn't be that affected. But sadly mods like SimRealist or WhickedWhims are still broken which are essential for me. Eh might as well wait a few more days. Funny thing is I haven't played in like 4 months or so and RIGHT NOW when I finally wanna play it again, all stuff is borked.
